# Generated by Django 5.1.4 on 2024-12-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=255)),
                ('servicio', models.CharField(max_length=255)),
                ('fecha_hora', models.CharField(max_length=255)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('contacto', models.CharField(max_length=255)),
            ],
        ),
    ]
